// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjtbrdcjqfvuadkpynss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqdGJyZGNqcWZ2dWFka3B5bnNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxOTk4NDUsImV4cCI6MjA1Nzc3NTg0NX0.f_uscpdWtRpcrUh-tDRXdKAlOuK5Cf9GK5gKyCf6yfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);